### ISSUE TITLE
How to do submit form?

### ISSUE THREAD

**Issue by yozawiratama** [redexp/express-engine-jsx#2]

**Comment by redexp** [comment]
Don't understand the question

**Comment by bugdriven** [comment]
It works as expected for me. Just ordinary react/html. Try something like this:
<form method="put" name="setName" >
<input id="Id" name="Id" type="hidden" value={id} />
Input name here: <input name="Surname" value={surname} />
<button type="submit" formaction="/setName">Save</button>
</form>
You need the "setName" server endpoint of course.

**Comment by bugdriven** [comment]
`<form method="put" name="setName" >
<input id="Id" name="Id" type="hidden" value={id} />
Input here: <input name="Surname" value={surname} />
<button type="submit" formaction="/setName">Save</button>
</form>`

**Comment by yozawiratama** [comment]
sorry i dont explain more before,

I mean, I thought it looks like react

I just want to know how dom manipulation works in jsx with this library

**Comment by redexp** [comment]
This is template engine for `express` like servers which uses `ReactDOM.renderToStaticMarkup` so there no any dom manipulations
