### ISSUE TITLE
Build error TS2307: Cannot find module 'node:vm'

### ISSUE THREAD

**Issue by ua9msn** [redexp/express-engine-jsx#6]
Hi there
Trying to use the library as engine i've got the error : 
```
node_modules/express-engine-jsx/index.d.ts:31:32 - error TS2307: Cannot find module 'node:vm' or its corresponding type declarations.
31         scriptOptions?: import('node:vm').ScriptOptions,
                             ~~~~~~~~~
Found 1 error(s).
```
The code of my app is not matter since it's empty nestjs app and engine is not set
Versions: 
node v14.17.6
"@types/node": "^14.17.34"
"typescript": "^4.5.2",

**Comment by redexp** [comment]
@ua9msn `node:vm` means that should be imported exactly node internal `vm` module. I changed to `import('vm')` but I should warn you that I added `index.d.ts` more like for autocomplete in editor, I never tested it in ts environment
